### ISSUE TITLE
boot the kernel

### ISSUE THREAD

**Issue by cljidkx** [jaredmcneill/quartz64_uefi#23]
hello， I want to replace uboot with uefi.  Although uefi can start normally, I don't know how he boots the system and what kind of partition structure needs to be created on the disk.  When using uboot, the partition structure of my SD card is uboot, boot, recovery, rootfs. What kind of structure do I need after using uefi?  I compiled grub.efi for aarch64, I don't know how he uses it.  What else do I need to boot the system after burning the uefi image?

**Comment by sickosarm** [comment]
You have to use a uefi iso to install your OS somewhere else. There is a list in this repo (netbsd, ubuntu ...) I have also installed Fedora 35 without any trouble.
