### ISSUE TITLE
[device request] Odroid M1 support planned?

### ISSUE THREAD

**Issue by Strit** [jaredmcneill/quartz64_uefi#33]
I was just wondering if support for the rk3568 based Odroid M1 is possibly gonna happen?

It's very much like the Quartz64 regarding I/O and uses the same SoC as the StationPC M2.

Here's the product page: https://www.hardkernel.com/shop/odroid-m1-with-8gbyte-ram/

I have the device and would be willing to do some testing.

**Comment by S199pWa1k9r** [comment]
It's nice to see that the Manjaro team is interested in EDK2 UEFI.

A few notes:

1. What OS do you want to test?
2. Station-M2 is based on RK3566 and Odroid-M1 is based on RK3568.
3. Odroid-M1 is more like FriendlyARM R5S.
4. You can try adding support for Odroid-M1 yourself, I tried it and it worked for Radxa Rock-3A and Radxa R5S.

**Comment by Strit** [comment]
1. Primarily Manjaro with EFI would be my tests.
2. Ah you're right. I was thinking of the Station P2. Sorry.
3. Don't really know that board, but I've seen kernel patches for it, I think.
4. I'm not a programmer at all and looking at the PR's it looks to adds a bunch of files for each board to be supported. I would likely just mess thinks up.

**Comment by S199pWa1k9r** [comment]
OK, Nice.
I am very familiar with Furkan Kardame from Manjaro TEAM.

I don't have an Odroid-M1 but I'm interested in adding more RK356x boards.
And I'm ready to help you, I can explain how easy it is to do. 
I also had little idea about Tianocore EDKII, quite recently, but believe me it was not difficult.
You just need to study in detail the distinctive features of your board. To do this, just look at the schemes and DTS files.
If you can still do a couple of FreeBSD test runs for me on your board, that would be fun.

**Comment by S199pWa1k9r** [comment]
> 1. Primarily Manjaro with EFI would be my tests.
> 2. Ah you're right. I was thinking of the Station P2. Sorry.
> 3. Don't really know that board, but I've seen kernel patches for it, I think.
> 4. I'm not a programmer at all and looking at the PR's it looks to adds a bunch of files for each board to be supported. I would likely just mess thinks up.

If you have a ready image I can check on RADXA Rock 3A

**Comment by Strit** [comment]
> > 1. Primarily Manjaro with EFI would be my tests.
> > 2. Ah you're right. I was thinking of the Station P2. Sorry.
> > 3. Don't really know that board, but I've seen kernel patches for it, I think.
> > 4. I'm not a programmer at all and looking at the PR's it looks to adds a bunch of files for each board to be supported. I would likely just mess thinks up.
> 
> If you have a ready image I can check on RADXA Rock 3A

You can try one of [these images](https://github.com/manjaro-arm/generic-efi-images/releases/tag/20221010) on the Rock 3A with the UEFi firmware. It boots on Pinebook Pro and Odroid N2 with Tow-Boot.

**Comment by S199pWa1k9r** [comment]
The good news is that Manjaro is launching on Rock3A and moving into multiplayer mode.
Work Console/HDMI(efifb)/USB.

The bad news is that gmac doesn't work.

Starting version 251.5-1-arch
[ 7.281009] stmmaceth PRP0001:03: IRQ macirq not found

**Comment by Strit** [comment]
yeah, the gmac issue is with the DTB. We fixed it in our kernels, but the kernels used in the efi images don't have DTBs.

**Comment by rpardini** [comment]
> The bad news is that gmac doesn't work.
> 
> Starting version 251.5-1-arch [ 7.281009] stmmaceth PRP0001:03: IRQ macirq not found

Funny, I have that same/similar problem on the Quartz64a itself. I updated the DTB for edk2 with the DTB from the (6.1.8) kernel, but still nothing. Using u-boot/device tree it works...

**Comment by S199pWa1k9r** [comment]
If you rebuild uefi with FDT support and use the DTB file from your version of Linux, I don't think you will see any difference with u-boot.

**Comment by sickosarm** [comment]
I have used DTB long tlrme ago with this efi boot and Linux using startup.nsh and there is  a significant difference, lowering performance. I thought It was because the memory is set at low speed looking  at the code  but don't have enough knowlegde.

**Comment by jaredmcneill** [comment]
Closing this thread as I don't have the hardware to add support. Please submit a pull request if you have changes to enable support.
