### ISSUE TITLE
would it be possible to port this to the rock 5b

### ISSUE THREAD

**Issue by hannescam** [jaredmcneill/quartz64_uefi#36]
it would be amazing to be able to use any arm64 efi os on the rock 5b

**Comment by kettenis** [comment]
I started looking into this. We need UEFI support for OpenBSD and the Rockchip U-Boot fork does not have that enabled.

**Comment by hannescam** [comment]
oh but are there chances to make the rock 5b uefi or means that it isnt possible

**Comment by S199pWa1k9r** [comment]
I think we should all pay attention to this repository
https://gitlab.com/rk3588_linux/rk/uefi-monorepo/-/tree/linux-5.10-gen-rkr3.1/edk2-platforms/Platform/Rockchip/RK3568
https://gitlab.com/rk3588_linux/rk/uefi-monorepo/-/tree/linux-5.10-gen-rkr3.1/edk2-platforms/Silicon/Rockchip/RK3568

**Comment by kettenis** [comment]
Given the quality of the code in the Rockchip fork of u-boot, I'm not sure about that.

**Comment by Googulator** [comment]
There's somewhat newer code here: https://github.com/chainsx/edk2-rk3588

Unfortunately the graphical output drivers in this are largely nonfunctional (only supporting eDP on the same pins Rock 5B uses for HDMI, with a single hardcoded display configuration used by Rockchip's developers). ~I'm attempting to port DisplayDxe from this repository onto chainsx's codebase.~ EDIT: sadly, the HDMI transmitter IP core in the 3588 is completely different from the one in the 356x.

**Comment by RadxaYuntian** [comment]
This port is currently able to boot Windows on ROCK 5B: https://github.com/edk2-porting/edk2-rk35xx

Not sure if it's feasible to merge the 2 projects together.

**Comment by hannescam** [comment]
please focus more on supporting all major linux distros not windows 
and please get hdmi working

**Comment by S199pWa1k9r** [comment]
HDMI already working

**Comment by jaredmcneill** [comment]
No plans to support RK3588 in this repo.

**Comment by hannescam** [comment]
good and does archlinux arm work?
