### ISSUE TITLE
Porting edk2 into rock5 rk3588

### ISSUE THREAD

**Issue by gesangtome** [jaredmcneill/quartz64_uefi#42]
Hi sir, I'm interested in your project and trying to port edk2 to rk3588, But it failed to start :(, I see that most of the rockchip drivers write bits to the BASE ADDR of some hardware module, but I can't find them in datasreet. May I ask you a question? Looking forward to your reply.

**Comment by S199pWa1k9r** [comment]
I hope you know that there are at least two threads on the Radxa forum discussing edk2 uefi for Rock5B.

 And uefi on Rock5B partially works.

https://forum.radxa.com/t/uefi-edk2-on-the-rock-5b/12642?page=2
https://forum.radxa.com/t/windows-on-rock-5-mega-thread/12924

**Comment by gesangtome** [comment]
> I hope you know that there are at least two threads on the Radxa forum discussing edk2 uefi for Rock5B.
> 
>  And uefi on Rock5B partially works.
> 
> https://forum.radxa.com/t/uefi-edk2-on-the-rock-5b/12642?page=2
> https://forum.radxa.com/t/windows-on-rock-5-mega-thread/12924
> 

Thank sir, I see everyone's efforts and even though I can't read Russian, the translation software will help me and I may be able to follow your discussion. excited!
