### ISSUE TITLE
Would 16MB spi flash enough for this uefi?

### ISSUE THREAD

**Issue by amazingfate** [jaredmcneill/quartz64_uefi#43]
I have radxa rock3a with a 16MB spi flash on board.
Now we create a 33MB image with a 16MB env partition. Is this partition necessary?
Sector 32768(16MB) is the start of linux boot partition according to [rockchip's document](https://opensource.rock-chips.com/wiki_Partitions).

**Comment by amazingfate** [comment]
Verified on rock3a, 16 MB is enough.

**Comment by PrestarLin** [comment]
> Verified on rock3a, 16 MB is enough.

how to flash it?my orangepi 3b have 16mb spi flash, but when i dd it , it say '/dev/mtdblock0': No space left on device

**Comment by hangedfish** [comment]
How did you do that? Can you provide a guide document?

**Comment by amazingfate** [comment]
I have't played with this firmware firmware for a long time, and I lost my change to source code. But I think just removing the 16MB env partition for spi flash should be okay.
