### ISSUE TITLE
Support for ROCK 3C model ?

### ISSUE THREAD

**Issue by sec** [jaredmcneill/quartz64_uefi#54]
Hi,
How much effort / what's needed to add support for ROCK 3C model? Looking at specs, it's also RK3566, same as Quartz64.
I tried image for Quartz64 (EFI on SD, OS on USB) + `u-boot` for 3C to boot FreeBSD. Loader booted, kernel started to boot but fail right at the start with `panic: Invalid bus configuration: acpi` :) ?

**Comment by jaredmcneill** [comment]
I cannot add support for boards that I don't have. But I'm happy to accept patches to add board support.

I _really_ don't recommend using images for different boards.

**Comment by sec** [comment]
@jaredmcneill I get that :) But for example ROCK 3C is very similar to Quartz64-B in both hardware and schematics. In fact, using DTB from the second one, I'm able to boot FreeBSD and have almost everything working except NVMe (looks like no support yet in kernel) and one or two USB ports. Hence the question was, what's needed and how to start to add support for new board.
