### ISSUE TITLE
Trouble with ethernet after reverting to uboot Quart64 Model A

### ISSUE THREAD

**Issue by t0mare** [jaredmcneill/quartz64_uefi#61]
I am having trouble getting the network card working when reverting to uboot and arch/manjaro after using the EDK2 with ESXI. I can't find any settings that could explain this. The board still works when booting back into EDK2 and ESXI. Any tips would help.

Thanks
Tom

**Comment by jaredmcneill** [comment]
I'm not aware of anything that could cause this, assuming you have used a clean eMMC / SD card.
