### ISSUE TITLE
Add support for Geniatexh XPI-3566 ZERO

### ISSUE THREAD

**Issue by extrowerk** [jaredmcneill/quartz64_uefi#66]
Vendor link: https://www.geniatech.com/product/xpi-3566-zero/

I posess the board (2/8 variant) and willing to help and provide info and logs.
My plan is to boot OpenBSD with HDMI output on it.

**Comment by extrowerk** [comment]
I have attaempted to flash the Firefly ROC-RK3566-PC EDK2 build, as the hw is pretty similar, but now the board doesn't boot anymore, and i can't seem to switch it into maskmode :( I have tried the RCEY and the RESET buttons, but no dice.
Sadly the spec doesn't tells anything about shorting the pads and the PCB doesn't have marking for this either. I have contacted the manufacturer, lets see if i get any answer.

**Comment by extrowerk** [comment]
I have managed to restore the board with shorting 2 pads on the board, see more info here: https://extrowerk.com/2023-10-30/Geniatech-XPI-3566-ZERO-SBC.html

**Comment by jaredmcneill** [comment]
I don't have access to this board. Happy to accept a port to it if you submit one!

**Comment by extrowerk** [comment]
> I don't have access to this board. Happy to accept a port to it if you submit one!

I have attempted to make one here: https://github.com/jaredmcneill/quartz64_uefi/pull/71
However as this board doesn't have any SD-card slot, only an on-board eMMC and USB ports, and i was unable to get EDK2 start from eMMC. Do you have any hints or idea?
I have tried to flash the image on LBA 0, or to LBA 64,but it didn't helps.
Any help would be greatly appreciated.
